-- Esquemna Refactorizado Maersk (V3 - Supabase Ready)
-- Ordenado por dependencias para evitar errores de Foreign Key.

-- 0. Funciones Utilitarias (Deben crearse primero)
create or replace function update_updated_at_column()
returns trigger as $$
begin
    new.updated_at = now();
    return new;
end;
$$ language plpgsql;

-- 1. Tablas Base (Sin dependencias externas)

-- 1.1 Organizaciones
create table public.organizaciones (
  id_organizacion serial not null,
  nombre character varying(200) not null,
  rut character varying(20) null,
  estado character varying(20) null default 'activo'::character varying,
  metadata jsonb null default '{}'::jsonb,
  configuracion jsonb null default '{}'::jsonb,
  logo_url text null,
  contacto_email character varying(255) null,
  contacto_telefono character varying(50) null,
  activo boolean null default true,
  nit character varying(50) null,
  contacto_nombre character varying(100) null,
  direccion text null,
  fecha_inicio date null default CURRENT_DATE,
  notas text null,
  created_at timestamp with time zone null default now(),
  updated_at timestamp with time zone null default now(),
  constraint organizaciones_pkey primary key (id_organizacion),
  constraint organizaciones_rut_key unique (rut)
);

create trigger update_organizaciones_updated_at before update on organizaciones for each row execute function update_updated_at_column ();

-- 1.2 Bloques Horarios
create table public.bloques_horarios (
  id_bloque integer not null,
  descripcion text not null,
  hora_inicio time without time zone not null,
  hora_fin time without time zone not null,
  constraint bloques_horarios_pkey primary key (id_bloque)
);

-- 1.3 Event Categories
create table public.event_categories (
  id serial not null,
  name text not null,
  created_at timestamp with time zone not null default timezone ('utc'::text, now()),
  constraint event_categories_pkey primary key (id),
  constraint event_categories_name_key unique (name)
);

-- 1.4 Registro Personas (Independiente)
create table public.registro_personas (
  id bigint generated by default as identity not null,
  nombre text not null,
  rut text null,
  categoria text null,
  constraint registro_personas_pkey primary key (id),
  constraint registro_personas_id_key unique (id)
);

-- 1.5 Roles
create table public.roles (
  id_rol serial not null,
  codigo character varying(50) not null,
  nombre character varying(100) not null,
  descripcion text null,
  nivel integer null default 0,
  es_sistema boolean null default false,
  created_at timestamp with time zone null default now(),
  constraint roles_pkey primary key (id_rol),
  constraint roles_codigo_key unique (codigo)
);

-- 1.6 Módulos
create table public.modulos (
  id_modulo serial not null,
  codigo character varying(50) not null,
  nombre character varying(100) not null,
  descripcion text null,
  version character varying(20) null default '1.0.0'::character varying,
  es_core boolean null default false,
  requiere_modulos jsonb null default '[]'::jsonb,
  configuracion_schema jsonb null,
  icono character varying(50) null,
  activo boolean null default true,
  orden integer null default 0,
  precio_mensual numeric(10, 2) null default 0.00,
  created_at timestamp with time zone null default now(),
  updated_at timestamp with time zone null default now(),
  constraint modulos_pkey primary key (id_modulo),
  constraint modulos_codigo_key unique (codigo)
);

create trigger update_modulos_updated_at before update on modulos for each row execute function update_updated_at_column ();

-- 1.7 Choferes
create table public.choferes (
  id_chofer bigint generated by default as identity not null,
  rut_chofer text not null,
  nombres_chofer text null,
  apellidos_chofer text null,
  id_cardholder text null,
  id_credencial text null,
  numero_documento text null,
  fecha_nacimiento date null,
  fecha_emision date null,
  fecha_vencimiento date null,
  foto_match text null,
  foto_cara_carnet text null,
  email character varying(255) null,
  creado_en timestamp with time zone null default now(),
  actualizado_en timestamp with time zone null default now(),
  constraint choferes_pkey primary key (id_chofer),
  constraint choferes_rut_chofer_key unique (rut_chofer)
);

-- 2. Tablas Dependientes Nivel 1

-- 2.1 Depósitos (Depende de Organizaciones)
create table public.depositos (
  id uuid not null default gen_random_uuid (),
  id_organizacion integer not null,
  nombre character varying(50) not null,
  descripcion text null,
  direccion character varying(255) null,
  activo boolean null default true,
  creado_en timestamp with time zone null default now(),
  actualizado_en timestamp with time zone null default now(),
  constraint depositos_pkey primary key (id),
  constraint depositos_nombre_key unique (nombre),
  constraint depositos_organizacion_fkey foreign key (id_organizacion) references organizaciones (id_organizacion) on delete cascade
);

-- 2.2 Camaras (Depende de Depósitos)
create table public.camaras (
  id uuid not null default gen_random_uuid (),
  id_deposito uuid not null,
  nombre text not null,
  id_externo text null,   -- ID de cámara en sistema VMS/Externo
  ubicacion text null,
  estado text default 'activa',
  metadata jsonb default '{}'::jsonb,
  created_at timestamp with time zone null default now(),
  updated_at timestamp with time zone null default now(),
  constraint camaras_pkey primary key (id),
  constraint camaras_deposito_fkey foreign key (id_deposito) references depositos (id) on delete cascade
);

-- 2.3 Módulo Permisos (Depende de Módulos)
create table public.modulo_permisos (
  id serial not null,
  id_modulo integer not null,
  codigo_permiso character varying(100) not null,
  nombre character varying(100) not null,
  descripcion text null,
  categoria character varying(50) null,
  created_at timestamp with time zone null default now(),
  constraint modulo_permisos_pkey primary key (id),
  constraint modulo_permisos_id_modulo_codigo_permiso_key unique (id_modulo, codigo_permiso),
  constraint modulo_permisos_id_modulo_fkey foreign key (id_modulo) references modulos (id_modulo) on delete cascade
);

-- 2.4 Organización Módulos (Depende de Org y Módulos)
create table public.organizacion_modulos (
  id serial not null,
  id_organizacion integer not null,
  id_modulo integer not null,
  activo boolean null default true,
  configuracion jsonb null default '{}'::jsonb,
  fecha_activacion timestamp with time zone null default now(),
  fecha_expiracion timestamp with time zone null,
  activado_por uuid null,
  notas text null,
  created_at timestamp with time zone null default now(),
  updated_at timestamp with time zone null default now(),
  constraint organizacion_modulos_pkey primary key (id),
  constraint organizacion_modulos_unico unique (id_organizacion, id_modulo),
  constraint organizacion_modulos_organizacion_fkey foreign key (id_organizacion) references organizaciones (id_organizacion) on delete cascade,
  constraint organizacion_modulos_modulo_fkey foreign key (id_modulo) references modulos (id_modulo) on delete cascade
);

create trigger update_organizacion_modulos_updated_at before update on organizacion_modulos for each row execute function update_updated_at_column ();

-- 2.5 Licencias Conducir (Depende de Choferes)
create table public.licencias_conducir (
  id_licencia bigint generated by default as identity not null,
  id_chofer bigint not null,
  rut text null,
  nombres text null,
  apellidos text null,
  direccion text null,
  clase text null,
  fecha_emision date null,
  fecha_vencimiento date null,
  foto_licencia text null,
  creado_en timestamp with time zone null default now(),
  constraint licencias_conducir_pkey primary key (id_licencia),
  constraint licencias_conducir_chofer_fkey foreign key (id_chofer) references choferes (id_chofer) on delete cascade
);

-- 3. Tablas Dependientes Nivel 2 (Dependen de N1 o combinanciones)

-- 3.1 Rol Modulo Permisos (Depende de Roles, Módulos, Permisos)
create table public.rol_modulo_permisos (
  id serial not null,
  id_rol integer not null,
  id_modulo integer not null,
  id_permiso integer not null,
  created_at timestamp with time zone null default now(),
  constraint rol_modulo_permisos_pkey primary key (id),
  constraint rol_modulo_permisos_unico unique (id_rol, id_modulo, id_permiso),
  constraint rol_modulo_permisos_rol_fkey foreign key (id_rol) references roles (id_rol) on delete cascade,
  constraint rol_modulo_permisos_modulo_fkey foreign key (id_modulo) references modulos (id_modulo) on delete cascade,
  constraint rol_modulo_permisos_permiso_fkey foreign key (id_permiso) references modulo_permisos (id) on delete cascade
);

-- 3.2 Usuarios (Depende de Org, Roles y Opcionalmente Depositos)
create table public.usuarios (
  id uuid not null default gen_random_uuid (),
  id_organizacion integer not null,
  id_deposito uuid null,
  id_rol integer null,
  rut text null unique,
  nombre text not null,
  apellidos text null,
  email text not null unique,
  password text null,
  telefono text null,
  cargo text null,
  estado character varying(20) default 'activo',
  avatar_url text null,
  ultima_sesion timestamp with time zone null,
  metadata jsonb null default '{}'::jsonb,
  created_at timestamp with time zone not null default timezone ('utc'::text, now()),
  updated_at timestamp with time zone not null default timezone ('utc'::text, now()),
  constraint usuarios_pkey primary key (id),
  constraint usuarios_organizacion_fkey foreign key (id_organizacion) references organizaciones (id_organizacion) on delete cascade,
  constraint usuarios_deposito_fkey foreign key (id_deposito) references depositos (id) on delete set null,
  constraint usuarios_rol_fkey foreign key (id_rol) references roles (id_rol) on delete set null
);

create trigger update_user_updated_at before update on usuarios for each row execute function update_updated_at_column ();

-- 4. Tablas Dependientes de Usuarios y Otros

-- 4.1 System Audit Logs (Depende de Usuarios)
create table public.system_audit_logs (
  id bigint generated by default as identity not null,
  user_id uuid null,
  action text not null,
  table_name text null,
  record_id text null,
  details jsonb null default '{}'::jsonb,
  ip_address text null,
  user_agent text null,
  created_at timestamp with time zone not null default timezone ('utc'::text, now()),
  constraint system_audit_logs_pkey primary key (id),
  constraint system_audit_logs_user_fkey foreign key (user_id) references usuarios (id) on delete set null
);

-- 4.2 Agendamientos (Depende de Usuarios, Choferes, Bloques)
create table public.agendamientos (
  id_agendamiento bigint generated by default as identity not null,
  id_chofer bigint null,
  fecha_agendada date not null,
  id_bloque integer not null,
  patente_vehiculo text null,
  identificador_container text null,
  creado_en timestamp with time zone null default now(),
  constraint agendamientos_pkey primary key (id_agendamiento),
  constraint agendamientos_bloque_fkey foreign key (id_bloque) references bloques_horarios (id_bloque),
  constraint agendamientos_chofer_fkey foreign key (id_chofer) references choferes (id_chofer)
);

-- 4.3 Geolocation Logs (Depende de Usuarios)
-- Importante: Debe ir antes que la función que lo usa
create table public.geolocation_logs (
  id bigint generated by default as identity not null,
  user_id uuid not null,
  latitude double precision not null,
  longitude double precision not null,
  action_type text not null,
  created_at timestamp with time zone not null default timezone ('utc'::text, now()),
  constraint geolocation_logs_pkey primary key (id),
  constraint geolocation_logs_user_fkey foreign key (user_id) references usuarios (id)
);

-- 5. Funciones Requeridas para Triggers

-- 5.1 Función Geolocalización
create or replace function fn_log_geolocation()
returns trigger as $$
begin
    if new.latitude is not null and new.longitude is not null then
        insert into public.geolocation_logs (user_id, latitude, longitude, action_type)
        values (new.user_id, new.latitude, new.longitude, tg_argv[0]);
    end if;
    return new;
end;
$$ language plpgsql;

-- 6. Tablas Operativas y Triggers

-- 6.1 Registro Choferes (Depende de Depositos, Agendamientos, Choferes, Usuarios)
create table public.registro_choferes (
  id_registro bigint generated by default as identity not null,
  id_deposito uuid not null,
  codigo_acceso text not null,
  id_usuario uuid null,
  id_chofer bigint null,
  id_agendamiento bigint null,
  rut_a_validar text null,
  resultado_match boolean null,
  patente_ingresada text null,
  container_ingresado text null,
  carga_peligrosa boolean null,
  tipo_vehiculo text null,
  estado_validacion character varying(20) null default 'pendiente'::character varying,
  fecha_validacion timestamp with time zone null,
  usuario_validacion uuid null,
  motivo_rechazo text null,
  fecha_visita timestamp with time zone null,
  foto_bl text null,
  email_chofer character varying(255) null,
  creado_en timestamp with time zone null default now(),
  constraint registro_choferes_pkey primary key (id_registro),
  constraint registro_choferes_deposito_fkey foreign key (id_deposito) references depositos (id) on delete cascade,
  constraint registro_choferes_agendamiento_fkey foreign key (id_agendamiento) references agendamientos (id_agendamiento),
  constraint registro_choferes_chofer_fkey foreign key (id_chofer) references choferes (id_chofer),
  constraint registro_choferes_usuario_fkey foreign key (id_usuario) references usuarios (id),
  constraint registro_choferes_validador_fkey foreign key (usuario_validacion) references usuarios (id)
);

create index idx_registro_choferes_deposito on public.registro_choferes (id_deposito);

-- 6.2 Access Logs
create table public.access_logs (
  id uuid not null default gen_random_uuid (),
  id_deposito uuid not null,
  user_id uuid not null,
  visitor_rut text not null,
  visitor_name text not null,
  visit_destination text not null,
  vehicle_type text not null,
  license_plate text null,
  latitude double precision null,
  longitude double precision null,
  license_plate_photo_url text null,
  created_at timestamp with time zone not null default timezone ('utc'::text, now()),
  constraint access_logs_pkey primary key (id),
  constraint access_logs_deposito_fkey foreign key (id_deposito) references depositos (id) on delete cascade,
  constraint access_logs_user_fkey foreign key (user_id) references usuarios (id)
);

create trigger tr_log_geo_access
after insert on access_logs for each row
execute function fn_log_geolocation ('INGRESO');

-- 6.3 Incidents
create table public.incidents (
  id uuid not null default gen_random_uuid (),
  id_deposito uuid not null,
  user_id uuid null,
  category_id integer null,
  detail text not null,
  zona_incidente text null,
  prioridad text null,
  latitude double precision null,
  longitude double precision null,
  photo_url text null,
  manual_date timestamp with time zone null,
  created_at timestamp with time zone not null default timezone ('utc'::text, now()),
  constraint incidents_pkey primary key (id),
  constraint incidents_deposito_fkey foreign key (id_deposito) references depositos (id) on delete cascade,
  constraint incidents_user_fkey foreign key (user_id) references usuarios (id),
  constraint incidents_category_fkey foreign key (category_id) references event_categories (id)
);

create trigger tr_log_geo_incident
after insert on incidents for each row
execute function fn_log_geolocation ('NOVEDAD');

-- 6.4 Gate Controls
create table public.gate_controls (
  id uuid not null default gen_random_uuid (),
  id_deposito uuid not null,
  id_camara uuid null,
  user_id uuid not null,
  license_plate text not null,
  validacion_patente boolean null default false,
  license_plate_photo_url text null,
  container_seal text null,
  container_seal_photo_url text null,
  container_status text null,
  container_interior_photo_url text null,
  observations text null,
  bookmark text null,
  latitude double precision null,
  longitude double precision null,
  created_at timestamp with time zone not null default timezone ('utc'::text, now()),
  constraint gate_controls_pkey primary key (id),
  constraint gate_controls_deposito_fkey foreign key (id_deposito) references depositos (id) on delete cascade,
  constraint gate_controls_camara_fkey foreign key (id_camara) references camaras (id) on delete set null,
  constraint gate_controls_user_fkey foreign key (user_id) references usuarios (id)
);

create trigger tr_log_geo_gate
after insert on gate_controls for each row
execute function fn_log_geolocation ('GATE');
